name: generate token

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unzip Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD }} scripts.zip
      
      - name: generate token
        run: python tokengen.py
          
      - name: Zip files
        run: zip -P ${{ secrets.ZIP_PASSWORD }} scripts.zip app.py tokengen.py token.json
      
      - name: Cleanup Files
        if: always()
        run: rm -f app.py tokengen.py token.json

      - name: commit files
        run: |
          rm -rf __pycache__
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Token Updated!" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

permissions:
  contents: write
